### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by airassist** [benelori/flight_assist#5]
Please provide a list of all the strings and their translations

**Comment by airassist** [comment]
So.... let.s start by page:

Start page: picture and with the text on it:
**ENG**

**Was your flight cancelled? Did you have flight delay?**
Each passenger may receive a compensation up to **€600**!
Passenger rights are protected under EU regulation 261/2004!

Get to know more...

**RO**

**Zborul tău a avut întârziere sau a fost anulat?**
Probabil poți avea dreptul la o compensație de până la 600€!
Drepturile pasagerilor sunt protejate conform Regulamentului UE 261/2004!

Află mai multe...

**HU**
**Késett vagy törölték a járatod?**
Utasonkénti kártérítés akár ** 600 € -ig** terjedően!
Az utasok jogait a 261/2004 EU rendelet védi!

Tuddj meg többet...

**Comment by airassist** [comment]
**How to claim** helyett **How it works** oldal (Hogyan működik; Cum funcționează)

EN
As per EC 261/2004, if your flight has a long delay, is cancelled or you were denied boarding, depending on the flight length, you may be eligible for a compensation up to 600€. Conditions are, that the departure or  arrival airport must be within the EU and the carrier must be registered in one of the EU member states.

Mostly the passengers do not know their rights and even if, they do not have enough time or knowledge to claim successfully as airlines often reject their claims with various references. Our service offers passengers professional help to successfully claim their rights with our five step approach:

1. Contact us with the flight you had a problem: provide us with the flight data and keep ready all your documentation of the flight (boarding pass, reservation, etc.). This takes up to five minutes for you.

2. We check the eligibility of your case with our methods and check any information about your flight. Less than a week after you contacted us, we let you know if your claim is entitled for compensation. All for free. 

3. If you accept our proposal, we take your case to the airline and continue to fight. From this point, you can relax, as we work for you.

4. If we succeed and the airline pays, we will transfer your agreed share to your bank account. In case, that for any reason, we should fail, you owe us nothing.

**Comment by airassist** [comment]
**RO**

În conformitate cu CE 261/2004, în cazul în care zborul tău are o întârziere, este anulat sau ţi-a fost refuzat îmbarcarea, în funcție de lungimea zborului, poți fi eligibil pentru o compensație de până la 600 €. O importantă condiție este, că aeroportul de plecare sau de sosire trebuie să se afle în UE și transportatorul trebuie să fie înregistrat în unul din statele membre ale UE.

În cea mai mare parte, pasagerii nu își cunosc drepturile și chiar dacă, nu au suficient timp sau cunoștințe pentru a revendica cu succes compensaţia, deoarece companiile aeriene resping adesea reclamaţile cu diverse referințe sau motive. Serviciul nostru oferă pasagerilor asistență profesională pentru a-și revendica drepturile cu ajutorul metodei noastre care cuprinde **patru** (az angolban 5 van, de ez a helyes. Ott meg at kell fogalmazzan - our method which includes 4 main steps) paşi:

1. Intră în contact cu noi privind zborul cu care ai avut o problemă: furnizează datele de zbor și păstrează toate documentele privind zborul (bilet de îmbarcare, rezervare etc.). Acest pas durează pentru tine maxim 5 minute.

2. Verificăm eligibilitatea cazului pe baza infromaţilor furnizate de către tine și verificăm orice informație la care avem acces despre zborul tău. (Baze de date, meteorologie, autorităţile aeronautice, etc.). Acest pas durează mai puțin de o săptămână după ce ne ai contactat şi după ce am făcut analiza te informăm dacă cazul are dreptul la despăgubire. Această verificare este gratis, tu poţi chiar să ne furnizezi mai multe cazuri, tot nu te costă nimic.

3. Dacă accepi propunerea noastră, ducem cazul tău la compania aeriană și continuăm să luptăm pentru drepturile tale. Din acest punct te poți relaxa, că noi lucrăm pentru cazul tău.

4. În cazul succesului când am primit de la compania aeriană suma, emitem factura pentru comisionul nostru (25%) și transferăm 75% din suma primită în contul tău bancar . În cazul în care, din orice motiv, nu reușim să obţinem compensaţia, nu ne datorezi nimic! Politica **No Win - No Fee**!

**Comment by airassist** [comment]
**HU**

Az Európai Tanács EC 261/2004 rendelete alapján, ha egy repülőjárat esetén járatkésés, járattörlés,  vagy visszautasított beszállás történik, a repülőút hosszának függvényében, az utasok jogosultak lehetnek akár 600€ kártérítésre személyenként! Fontos feltétel, hogy az indulási vagy az érkezési repülőtér  az EU területén belül legyen, illetve a légitársaság egyik EU-s tagállamban kell legyen regisztrálva.

A legtöbb esetben az utasok nem ismerik a jogaikat vagy ha mégis, idő vagy megfelelő tudás hiányában nem tudják sikeresen kártérítési követelésüket érvényesíteni, mivel a légitársaságok gyakran elutasítják ezeket, különböző okokra hivatkozva. A szolgáltatásunk segítséget nyújt az utasok számára jogos kártérítési követelésüket gyorsan és kényelmesen érvényesíteni:

1. Lépj velünk a kapcsolatba, ha késett a járatod, törölték a járatodat, vagy megtagadták a beszállást.  Szükségünk lesz a repülőjárat adataira (dátum, induló és célállomás, rövid leírás, hogy mi történt) és gyűjtsd össze az összes repülési okmányt (beszállókártyák, járatfoglalás, stb.) Ez a lépés számodra legtöbb 5 percet vesz igénybe.

2. Az általad megadott és a számunkra külön elérhető repülési adatok alapján (repülési adatbázisok, meteorológia jelentések, légi közlekedési hatóságok, stb.) ellenőrizzük kártérítési jogosultságod. Kevesebb mint egy héttel azután, hogy kapcsolatba léptél velünk, értesítünk, ha az eseted kártérítésre jogosult. Ez az ellenőrzés ingyenes.

3. Amennyiben az kártérítési követelésed jogos és ajánlatunkal egyetértesz, akkor készen állunk ezt nem-peres és peres úton egyaránt behajtani. Ettől a ponttól kezdve hátradölhetsz, mert mi közben végezzük a munkánk.

4. Siker esetén, a légitársaságtól beérkező kártérítést – a 25%-os sikerdíjunk levonását követően –  az általad megadott bankszámlaszámra azonnal átutaljuk. Ha bármilyen okból nem járnánk sikerrel, nem tartozol nekünk semmilyen díjjal! No Win - No Fee!

**Comment by airassist** [comment]
@benelori  Amugy kivesszük a ABOUT US oldal és HELYETTE egy kontakt oldalt csinálunk, egy egszerű űrlappal. Később, ha megvan a multistepform, az lesz helyette a "Check your eligibility" névvel.

**Comment by airassist** [comment]
Oldalnevek fordítása, sorrendben, ahogy jönnek: 
1. **EN** Your rights  **RO** Drepturile tale **HU** Jogaid
2. **EN** How it works  **RO** Cum funcționează **HU** Hogyan működik
3. **EN** FAQ  **RO** Întrebări frecvente **HU** Gyakori kérdések
4. **EN** Contact **RO** Contact **HU** Kapcsolat

**Comment by airassist** [comment]
All translations have been complete. However, the contact form is not 100% and we must make adjustments.

**Comment by benelori** [comment]
Please see my comments on the feedbacks epic:
https://github.com/benelori/flight_assist/issues/7#issuecomment-340284123

If there are any problems with the translations, then I will do them myself, just please tell me where and what to translate

**Comment by airassist** [comment]
See #7
